"""Keepalived template for VRRP-based IP failover (HA).

Deploys a Keepalived container with:
  - network_mode: host (required for VRRP multicast and ARP)
  - NET_ADMIN, NET_BROADCAST, NET_RAW capabilities
  - Generated keepalived.conf with health check against Traefik
  - Configurable virtual IP, interface, priority and VRRP password
"""
from __future__ import annotations

from .base import TemplateField
from .official import SingleContainerTemplate


class KeepalivedTemplate(SingleContainerTemplate):
    id = "keepalived"
    name = "Keepalived (HA failover)"
    description = (
        "IP flotante con VRRP para alta disponibilidad. "
        "Requiere 2 nodos con el mismo VRID y distinta prioridad. "
        "Incluye health check contra Traefik."
    )
    version = "1.0"
    icon = "🔄"
    services = ["keepalived"]
    image = "osixia/keepalived:2.0.20"
    container_name = "keepalived"
    fields = [
        TemplateField(key="virtual_ip", label="IP flotante (VIP)", type="text",
                      hint="La IP virtual compartida entre los nodos, ej: 192.168.1.100",
                      placeholder="192.168.1.100"),
        TemplateField(key="interface", label="Interfaz de red", type="text",
                      default="eth0",
                      hint="Interfaz del host donde se anuncia la VIP (eth0, bond0, ens18…)"),
        TemplateField(key="priority", label="Prioridad VRRP", type="text",
                      default="100",
                      hint="Nodo principal: 100, secundario: 50. El más alto gana la VIP"),
        TemplateField(key="vrid", label="VRRP Router ID", type="text",
                      default="51",
                      hint="Mismo ID en ambos nodos (1-255). Único por VIP en la red"),
        TemplateField(key="auth_pass", label="Contraseña VRRP", type="password",
                      hint="Misma en ambos nodos (máx 8 caracteres)"),
        TemplateField(key="check_port", label="Puerto de health check", type="text",
                      default="443",
                      hint="Puerto TCP a comprobar (443 = Traefik HTTPS)"),
        TemplateField(key="subnet_mask", label="Máscara de subred", type="text",
                      default="24", required=False,
                      hint="Bits de máscara para la VIP (24 = /24 = 255.255.255.0)"),
        TemplateField(key="data_path", label="Ruta de configuración", type="path",
                      default="/share/Container/keepalived",
                      hint="Donde se guarda keepalived.conf"),
    ]

    def _data(self, cfg: dict) -> str:
        return (cfg.get("data_path") or "/share/Container/keepalived").rstrip("/")

    def host_dirs(self, cfg):
        return [self._data(cfg)]

    def host_files(self, cfg):
        return {
            f"{self._data(cfg)}/keepalived.conf": _keepalived_conf(cfg),
        }

    def build_run_kwargs(self, cfg):
        d = self._data(cfg)
        return {
            "network_mode": "host",
            "cap_add": ["NET_ADMIN", "NET_BROADCAST", "NET_RAW"],
            "environment": {
                "KEEPALIVED_CUSTOM_CONFIG": "true",
            },
            "volumes": [
                f"{d}/keepalived.conf:/container/service/keepalived/assets/keepalived.conf:ro",
            ],
        }

    def success_notes(self, cfg):
        vip = cfg.get("virtual_ip", "?")
        iface = cfg.get("interface", "eth0")
        prio = cfg.get("priority", "100")
        return [
            f"🔄 Keepalived activo en {iface} con prioridad {prio}",
            f"🌐 VIP: {vip} — el nodo con mayor prioridad la mantiene",
            f"❤️ Health check: TCP :{cfg.get('check_port', '443')} cada 3s",
            "⚠️  Despliega otro Keepalived en el segundo nodo con MENOR prioridad y el MISMO VRID + contraseña",
        ]


def _keepalived_conf(cfg: dict) -> str:
    vip = cfg.get("virtual_ip", "192.168.1.100")
    iface = cfg.get("interface", "eth0")
    priority = cfg.get("priority", "100")
    vrid = cfg.get("vrid", "51")
    auth_pass = cfg.get("auth_pass", "secret")[:8]
    check_port = cfg.get("check_port", "443")
    mask = cfg.get("subnet_mask", "24")

    return f"""\
! Keepalived configuration — generated by comeback
! Deploy the same config on the secondary node with a lower priority.

vrrp_script chk_service {{
    script "/bin/sh -c '</dev/tcp/127.0.0.1/{check_port}'"
    interval 3
    weight -20
    fall 3
    rise 2
}}

vrrp_instance VI_1 {{
    state BACKUP
    interface {iface}
    virtual_router_id {vrid}
    priority {priority}
    advert_int 1
    nopreempt

    authentication {{
        auth_type PASS
        auth_pass {auth_pass}
    }}

    virtual_ipaddress {{
        {vip}/{mask} dev {iface}
    }}

    track_script {{
        chk_service
    }}
}}
"""
